baseurl = "https://iskovpin.ru"
title = "iskovpin"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Ivan Skovpin"
    description = "Ivan Skovpin's personal website"
    keywords = "blog,developer,personal"
    info = "PHP developer"
    avatarurl = "images/avatar.jpg"
    footercontent = "May the force be with you"

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true

   rtl = false

   # Specify light/dark colorscheme
   # Supported values:
   # "auto" (use preference set by browser)
   # "dark" (dark background, light foreground)
   # "light" (light background, dark foreground) (default)
   colorScheme = "auto"

   # Hide the toggle button, along with the associated vertical divider
   hideColorSchemeToggle = false

   # Series see also post count
   maxSeeAlsoItems = 5

   # Enable Twemoji
   enableTwemoji = true

   # Custom CSS
   customCSS = []

   # Custom SCSS
   customSCSS = []

   # Custom JS
   customJS = []

[taxonomies]
  series = "series"

[[params.social]]
    name = "hh.ru"
    icon = "fa fa-address-card"
    weight = 1
    url = "/ru/resume?utm=homepage"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 1
    url = "https://www.linkedin.com/in/iskovpin/?locale=en_US"
[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 2
    url = "https://github.com/iskovpin"
[[params.social]]
    name = "Mail"
    icon = "fa fa-envelope"
    weight = 3
    url = "mailto:mailbox@iskovpin.ru"


[languages]
    [languages.en]
        languagename = "EN"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

    [languages.ru]
        languagename = "RU"
        title = "iskovpin"

        [languages.ru.params]
            author = "Иван Сковпин"
            info = "PHP разработчик"
            description = "Иван Сковпин. Персональный веб-сайт"
            keywords = "php,разрабочик"

            [[languages.ru.params.social]]
                name = "Resume"
                icon = "fa fa-address-card"
                weight = 1
                url = "/ru/resume?utm=homepage"
            [[languages.ru.params.social]]
                name = "LinkedIn"
                icon = "fa fa-linkedin"
                weight = 1
                url = "https://www.linkedin.com/in/iskovpin"
            [[languages.ru.params.social]]
                name = "Github"
                icon = "fa fa-github"
                weight = 2
                url = "https://github.com/iskovpin"
            [[languages.ru.params.social]]
                name = "Mail"
                icon = "fa fa-envelope"
                weight = 3
                url = "mailto:mailbox@iskovpin.ru"

        [languages.ru.menu]
            [[languages.ru.menu.main]]
            name = "Обо мне"
            weight = 1
            url = "/ru/obo-mne/"

            [[languages.ru.menu.main]]
            name = "Блог"
            weight = 1
            url = "/ru/posts/"

