baseurl = "https://iskovpin.ru"
title = "iskovpin"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Ivan Skovpin"
    description = "Ivan Skovpin's personal website"
    keywords = "blog,developer,personal"
    info = "PHP developer"
    avatarurl = "images/avatar.jpg"
    footercontent = "May the force be with you"

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

[taxonomies]
  series = "series"

[[params.social]]
    name = "hh.ru"
    icon = "fa fa-address-card"
    weight = 1
    url = "https://spb.hh.ru/applicant/resumes/view?resume=f37d79e9ff02d1a8a00039ed1f537a626b5150"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 1
    url = "https://www.linkedin.com/in/iskovpin/?locale=en_US"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 2
    url = "https://github.com/iskovpin/"
[[params.social]]
    name = "Mail"
    icon = "fa fa-envelope"
    weight = 3
    url = "mailto:mailbox@iskovpin.ru"


[languages]
    [languages.en]
        languagename = "EN"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

    [languages.ru]
        languagename = "RU"
        title = "iskovpin"

        [languages.ru.params]
            author = "Иван Сковпин"
            info = "PHP разработчик"
            description = "Иван Сковпин. Персональный веб-сайт"
            keywords = "php,разрабочик"

        [languages.ru.menu]
            [[languages.ru.menu.main]]
            name = "Обо мне"
            weight = 1
            url = "/ru/obo-mne/"

